name: Continuous Integration
on:
  push:
    branches:
      - "work/*"

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: false #use cache

      - name: Cache LFS
        uses: actions/cache@v1
        with:
          path: .git/lfs/objects
          # In a push event this is the name of the branch (refs/heads/branch-name).
          # In a pull request this names the virtual merge (refs/pulls/123/merge).
          key: lfs-${{ github.ref }}
          # On a cache miss take the newest cache entry this branch has access to.
          restore-keys: lfs-

      - name: Pull LFS
        run: git lfs pull    
        
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
                    
      - name: restore packages
        run: yarn

      - name: Build action
        run: yarn build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Build and Commit action.js
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: 'dist/*/**'
          push: '-f'